config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'demos'   => 'static_pages#demos'
  get 'notes'   => 'static_pages#notes'

  get 'login'   => 'sessions#login'

  resource :sandbox
  resources :oldusers
  resources :accounts
  resources :mountains
  #rake routes to see the magic

end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mountain.rb
class Mountain < ApplicationRecord
  validates :planet, inclusion:{in: %w(Earth Mars), message: "ERROR - %{value} is not valid. The planet must only be Earth of Mars"}
  validate :tallest_mountain_height_per_planet, :valid_email, :mountain_empty, :valid_phone

  def mountain_empty
    if mountain == ''
      errors.add(:mountain, "ERROR - Mountain can not be empty")
      return false
    end
  end

  def tallest_mountain_height_per_planet
    if height == nil
      errors.add(:height, "ERROR - Height can not be empty")
      return false
    end

    unless (height > 999 &&
      planet == 'Earth' &&
      height <= 40000)||
      (height > 999 &&
      planet == 'Mars' &&
      height <= 90000)
      errors.add(:height, "ERROR - The smallest mountain must be at least 1000 feet and the tallest mountain on Earth is 40,000 ft., Mars is 90,000 ft")
    end
  end

  def valid_email
    unless record_added_by_email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      errors.add(:record_added_by_email, "ERROR - is not an email")
    end
  end

  def valid_phone
    if phone == nil
      errors.add(:phone, "ERROR - Phone can not be empty")
      return false
    end

    unless (phone.size >= 8 && phone.size <= 16)
      errors.add(:phone, "ERROR - a phone number must be between 9 and 16 digits")
    end
  end

end

app/models/old_user.rb
class User < ApplicationRecord
validate :valid_email


  def valid_email
    unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      errors.add(:email, "ERROR - is not an email")
    end
  end
end

app/models/sandbox.rb
class Sandbox < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.all
  end

  def show
    account
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      render :create
    else
      render :error
    end
  end

  def destroy
    account.destroy
    redirect_to "/accounts"
  end

  def edit
    account
  end

  def update
    account.update(account_params)
    redirect_to "/accounts"
  end

  def account_params
    params.require(:account).permit!
  end

  def account
    @account = Account.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :authenticate_user!

  def clean_phone
    mountain_params[:phone] = mountain_params[:phone].scan(/\d/).join
  end

  def index
    @mountains = Mountain.all.reverse
  end

  def show
    mountain
  end

  def mountain
    @mountain = Mountain.find(params[:id])
  end

  def edit
    mountain
  end

  def update
    clean_phone
    mountain.update(mountain_params)
    redirect_to "/mountains"
  end

  def mountain_params
    params.require(:mountain).permit!
  end

  def destroy
    mountain.destroy
  redirect_to "/mountains"
  end

  def new
    @mountain = Mountain.new
  end

def create
  clean_phone
  @mountain = Mountain.new(mountain_params)
  if @mountain.save
    render :create
  else
    render :new
  end
end

end

app/controllers/sandboxes_controller.rb
User = Struct.new(:id, :user, :fname, :lname, :email, :password)

class SandboxesController < ApplicationController
  def sandbox_params
    params.require(:sandbox).permit!
  end

  def create
    Sandbox.create(sandbox_params)
    # rails magic - a controller will by deaful render a view witht he same name as the action
  end

  def update
    set_post
    @post.update(sandbox_params)
    redirect_to "/sandbox"
  end

  def set_post
      @post ||= Sandbox.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController <  ApplicationController
  def login
    render :login
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    render :index
  end

  def about
    render :about
  end

  def contact
    render :contact
  end

  def demos
    render :demos
  end

  def notes
    render :notes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mountain_helper.rb
module MountainHelper
end

app/views/accounts/_account_record.erb
<br>
ID              :<%= account.id %><br>
Account Holder  :<%= account.accountholder %><br>
Location        :<%= account.location %><br>
created_at      :<%= account.created_at.to_s(:long) %><br>
updated_at      :<%= account.updated_at.to_s(:long) %><br>


<%= link_to "Show Account", account %>
<br>

app/views/accounts/create.erb
Create View
<br>

<%= simple_form_for @account do |f| %>
  <%= f.input :accountholder %>
  <%= f.input :location %>
  <% end %>

<a href="/accounts">Show all Accounts</a>

app/views/accounts/edit.erb
Edit Record

<%= simple_form_for @account do |f| %>
<%= f.input :accountholder %>
<%= f.input :location %>
<%= f.button :submit %>
<% end %>

app/views/accounts/index.erb
Accounts Index of ALL Records

<%= link_to 'Add Account', new_account_path %>

<% @accounts.each{|record| %>
<%= render('account_record', account:record)%>
<% } %>

app/views/accounts/new.erb
<%= simple_form_for @account do |f| %>
  <%= f.input :accountholder %>
  <%= f.input :location %>
  <%= f.button :submit %>
<% end %>

<br>
<%= link_to 'Back', accounts_path %>

app/views/accounts/show.erb
Accounts Show 1 Record
<br>

ID:             <%= @account.id %><br>
Account Holder: <%= @account.accountholder %><br>
Location:       <%= @account.location %><br>
Created:        <%= @account.created_at %><br>
Updated:        <%= @account.updated_at %><br>
<br>

<tr>
  <td><%= link_to "Index of all Accounts", accounts_path %> </td>
  <br>
  <td><%= link_to "Update Account Record", edit_account_path %></td>
  <br>
  <%= link_to 'Delete Record', @account, method: :delete, data: {confirm: 'Are you sure?'}%></td>
</tr>

app/views/layouts/_session.erb
&nbsp;<%= session[:fname]%>
&nbsp;<%= session[:lname]%>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "StevesSandbox" %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">StevesSandbox</a>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", "/"  %></li>
          <li><%= link_to "About", "/about"  %></li>
          <li><%= link_to "Demos", "/demos"  %></li>
          <li><%= link_to "Notes", "/notes"  %></li>
          <li><%= link_to "Contact", "/contact"  %></li>
          <% if current_user %>
            <li><%= link_to "Logout", "/users/sign_out", method: 'delete' %></li>
          <% else %>
            <li><%= link_to "Login", "/users/sign_in" %></li>
          <% end %>
          <li><%= link_to "SandBox", "/sandbox"  %></li>
          <li><%= link_to "Accounts", "/accounts"  %></li>
          <li><%= link_to "Mountains", "/mountains"  %></li>
          <li><%= link_to "#{current_user.email} Member Since #{current_user.created_at.year}"%></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <div class="col-lg-3">
        <div class="well sidebar-nav">
          <h3>Sidebar</h3>
          <ul class="nav nav-list">
            <li class="nav-header">Sidebar</li>
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div><!--/.well -->
      </div><!--/span-->
    </div><!--/row-->

    <footer>
      <p>&copy; Company 2017</p>
    </footer>

  </div> <!-- /container -->

</body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steve Test</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <a href="/">Home</a>
    <a href="/about">About</a>
    <a href="/demos">Demos</a>
    <a href="/notes">Notes</a>
    <a href="/contact">Contact</a>
    <a href="/login?fname=Buddy&lname=Shoes">Login</a>
    <a href="/sandbox">Sandbox</a>
    <a href="/users">Users</a>
    <a href="/accounts">Accounts</a>
    <a href="/mountains">Mountains</a>

  </head>

  <body>
    <br>
    <br>
    NOTE: Current Session = <%= render("layouts/session") %>
    <br>
    <%= yield %>
  </body>
</html>

app/views/mountains/_mountain_record.erb
<br>
<br>
ID        : <%= mountain.id %><br>
Mountain  : <%= mountain.mountain %><br>
Planet    : <%= mountain.planet%><br>
Height    : <%= mountain.height %><br>
Notes     : <%= mountain.notes %><br>
Phone     : <%= mountain.phone %><br>
Email     : <%= mountain.record_added_by_email %><br>

<%= link_to "Show Mountain", mountain %>
<br>

app/views/mountains/create.erb
Create View
<br>
<%= simple_form_for @mountain do |f| %>
  <%= f.input :mountain %>
  <%= f.input :height %>
  <%= f.input :notes %>
  <%= f.input :planet %>
  <%= f.input :phone %>
  <%= f.input :record_added_by_email %>
<% end %>

<a href="/mountains">Show all Mountains</a>

app/views/mountains/edit.erb
Edit Record

<%= simple_form_for @mountain do |f| %>
<%= f.input :mountain %>
<%= f.input :height %>
<%= f.input :notes %>
<%= f.input :planet %>
<%= f.input :phone %>
<%= f.input :record_added_by_email %>
<%= f.button :submit %>
<% end %>

app/views/mountains/index.erb
Mountains - Index of all Mountain Records

<%= link_to 'Add Mountain', new_mountain_path %>

<% @mountains.each{|record| %>
<%= render('mountain_record', mountain:record) %>
<% } %>

app/views/mountains/new.erb
<%= simple_form_for @mountain do |f| %>
  <%= f.input :mountain %>
  <%= f.input :height %>
  <%= f.input :notes %>
  <%= f.input :planet %>
  <%= f.input :phone %>
  <%= f.input :record_added_by_email %>
  <%= f.button :submit %>
<% end %>

<br>
<%= link_to 'Back', mountains_path %>

app/views/mountains/show.erb
Mountain Show 1 Record

<br>
ID        :<%= @mountain.id %><br>
Mountain  :<%= @mountain.mountain %><br>
Planet    :<%= @mountain.planet %><br>
Height    :<%= @mountain.height %><br>
Phone     :<%= @mountain.phone %><br>
Notes     :<%= @mountain.notes %><br>
email     :<%= @mountain.record_added_by_email %><br>
<br>

<%= link_to "Index of all Mountains", mountains_path %>
<br>
<%= link_to "Update Mountain Record", edit_mountain_path %>
<br>
<%= link_to 'Delete Record', @mountain, method: :delete, data: {confirm: 'Are you sure'} %>

app/views/sandboxes/_form.erb
<form action="/sandbox" method="POST">

ID:     <input type="hidden" name="id" value= "<%= user.id %>"  ><br>
User:   <input type='text' name="sandbox[user]"  value= "<%= user.user %>"  ><br>
First:  <input type='text' name="sandbox[fname]" value= "<%= user.fname %>" ><br>
Last:   <input type='text' name="sandbox[lname]" value= "<%= user.lname %>" ><br>
email:  <input type='text' name="sandbox[email]" value= "<%= user.email %>" ><br>
password:<input type='text' name="sandbox[password]"  value= <%= user.password %>  ><br>

app/views/sandboxes/_records.erb
ID      :<%= user.id %><br>
User    :<%= user.user %><br>
First   : <%= user.fname %><br>
Last    :<%= user.lname %><br>
Email   :<%= user.email %><br>
Password:<%= user.password %>
<br>
<%= button_to "edit", edit_sandbox_path(user), :method => "get" %>
<%= button_to "delete", user, :method => "delete" %>

<br><br>

app/views/sandboxes/create.erb
Create view
<br>
One Record Created
<br>

<% user = User.new(
  params["sandbox"][:id],
  params["sandbox"][:user],
  params["sandbox"][:fname],
  params["sandbox"][:lname],
  params["sandbox"][:email],
  params["sandbox"][:password]
  ) %>
<br>
<br>

<form action="/sandbox" method="POST">

ID:     <input type="hidden" name="id" value= "<%= user.id %>"  ><br>
User:   <%= user.user %><br>
First:  <%= user.fname %><br>
Last:   <%= user.lname %><br>
email:  <%= user.email %><br>
password:<%= user.password %><br>

<a href="/sandbox">Show All Sandbox Records></a>

app/views/sandboxes/destroy.erb
Destroy view
<br>
Record Deleted:

<%= p params[:format]%>

<%  user = Sandbox.find_by("id = #{params[:format]}")%>
<%  user.delete %>
<br>
Return to all users <a href="/sandbox">Users</a>

app/views/sandboxes/edit.erb
Edit

<%=params["format"] %>
<br>
<br>
<%= user = Sandbox.find_by("id = #{params[:format]}")%>
<br>
<br>
<%= render "form", user:user %>

<br>
  <input type="hidden" name="_method" value="patch" >
  <input type="submit" value="Submit" >
</form>
<br>

app/views/sandboxes/new.erb
New Records View

<br>
<br>

Please enter user: <br><br>

<form action="/sandbox" method="POST">

  User:   <input type='text' name="sandbox[user]"><br>
  First:  <input type='text' name="sandbox[fname]"><br>
  Last:   <input type='text' name="sandbox[lname]"><br>
  email:  <input type='text' name="sandbox[email]"><br>
  password:<input type='text' name="sandbox[password]"><br>

  <br>
  <input type="submit" value="Submit">
</form>
<br>

app/views/sandboxes/show.erb
Show
<a href="sandbox/new"> Add NEW Record</a>
<br>
<br>

<% user = Sandbox.all%>
<% user.each{|rec| rec %>
<%=render 'records', user:rec%>
<% } %>

app/views/static_pages/about.erb
About
<br>
Technology is changing rapidly. How a business fits into the changing landscape can be the difference between profit and loss.
<br><br>
Some of the technologies on the forefront:
<br><br>
1. AR / VR - Augmented Reality / Virtual Reality - AR and VR and very different. VR is for full immersion while AR is for Augmented immersion, like a heads-up display for a fighter pilot. With AR, static walls and resources will take on new shapes and controls to enhance the environment. Glasses and infrastructure are being developed to enable this technology.
<br><br>
2. Bots and Advanced IVR Technologies - IVR with speech enabled interfaces. Global Response is in an ideal position to take advantage of these technologies. As users decide to fail to an operator they can be continually refined to provide the best mix of service / cost / value.
<br><br>
3. IOT - The Internet of Things, Small gadgets that create a network of telemetry which can be used for alarms, monitoring, and active managment of things.
<br><br>
4. Cloud Services - Low capitol investment and unbounded scalability versus the ability to manage your own newwork and the associated uptimes.
<br><br>
5. React.js - A JavaScript framework that allows for real time web changes without page views, saving time. The alternative is Angular.
<br><br>
6. Xamerain - Mobile phone development. Let Xamaerain do the conversion into mobile development so you can stick with web technologies.
<br><br>
7. Ruby on Rails - Rapid web development environment. An elegant environment to enable the exploration of all of these technoliges.

app/views/static_pages/contact.erb
Contact
<br><br>
Stephen Shooster
<br>
steves@glogalresponse.com
<br>
954-973-7300

app/views/static_pages/demos.erb
Demos

app/views/static_pages/index.erb
Home

Welcome to Steve's Sandbox - A bare bones rails project for the purpose of testing various methods and ideas.

app/views/static_pages/notes.erb
Highlights:
db/Faker




set up github
  go to github and crate reposititory
  use the https method

set up database
console
rails generate (gives help messages)
  rails generate migration steves_sandbox  (creates a migration)
run migration
  rake db:migrate
  note:
    tables are plural
    classes are singular except controllers which are plural!
example:
rails generate migration CreateMountain mountain:text height:integer notes:text


rails generate migration AddFieldsToSandbox user:text email:text fname:text lname:text password:text
rails generate controller mountain   (not correct)
rails generate controller mountains (correct - notice plural)
rake db:migrate

rails generate migration AddFieldsToMountain planet:text
rails generate migration AddEmailToMountain record_added_by_email:text

.....
clean code with atom - open command pallette and choose autoindent
command - shift - p
seek auto indent
.....

Active Record environment
require File.expand_path('../../config/environment', __FILE__)

Active Record tests

Sandbox.where("id = 311")
Sandbox.where("id >= 211 and id <=400")
Sandbox.where "user LIKE '%Paul%'"

....
make nicely formated records
gem install table_print


action name must match the view name

... sql to test records ...
select * from sandboxes order by id desc limit 10;


>>>>>>>>>>
to start a new MVC
1. rails generate model user first_name last_name email age:integer
2. rake db:migrate

>>>>>>>


Adding Twitter Bootstrap
gem "twitter-bootstrap-rails"
bundle install
rails generate bootstrap:install static
rails generate simple_form:install --bootstrap
rails g bootstrap:layout [LAYOUT_NAME]